changes to version

diff --git a/scripts/install_dependencies b/scripts/install_dependencies
--- a/scripts/install_dependencies
+++ b/scripts/install_dependencies
@@ -2,7 +2,7 @@
 # Install nvm
 
 set -x  # Print commands and their arguments
-# set -e  # Exit immediately if a command exits with a non-zero status
+set -e  # Exit immediately if a command exits with a non-zero status
 
 # Install nvm
 curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
@@ -24,9 +24,11 @@ which mongod
 if [ $? -eq 1 ]; then
     sudo yum install -y openssl openssl11
 
+    source /etc/os-release
+
     echo "[mongodb-org-8.0]
-name=MongoDB 8.0 Community
-baseurl=https://repo.mongodb.org/yum/amazon/2/mongodb-org/8.0/x86_64/
+name=MongoDB Repository
+baseurl=https://repo.mongodb.org/yum/amazon/$VERSION/mongodb-org/8.0/x86_64/
 gpgcheck=1
 enabled=1
 gpgkey=https://pgp.mongodb.com/server-8.0.asc" | sudo tee /etc/yum.repos.d/mongodb-org-8.0.repo
